version: '3.4'

services:
  db:
     image: mysql:5.7
     environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: 1
       MYSQL_DATABASE: 'climate_rules'
     volumes:
       - dbdata:/var/lib/mysql
     restart: always

  climate-rules:
    depends_on:
       - db
    image: ${DOCKER_REGISTRY-}php:7.4.3
    ports:
      - "8181:8181"
    build:
      context: .
      dockerfile: ./Dockerfile
volumes:
    dbdata: